stages:          # List of stages for jobs, and their order of execution
  - build
  - visualize
  - containerize
  - release

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: maven:3.9.0-eclipse-temurin-19

  variables:
    MAVEN_CLI_OPTS: "-Dmaven.repo.local=.m2/repository"

  cache:
    paths:
      - .m2/repository

  script:
    - mvn $MAVEN_CLI_OPTS test package verify
  artifacts:
    when: always
    reports:
        junit: target/surefire-reports/TEST-*.xml
    paths:
      - target/*.jar
      - target/site/jacoco/jacoco.xml

visualize-job:
    stage: visualize
    image: registry.gitlab.com/haynes/jacoco2cobertura:latest

    script:
      - python /opt/cover2cover.py target/site/jacoco/jacoco.xml $CI_PROJECT_DIR/src/main/java/ > target/site/coverage.xml

    needs:
      - "build-job"

    dependencies:
      - build-job

    artifacts:
      reports:
        coverage_report:
          coverage_format: cobertura
          path: target/site/coverage.xml

containerize-job:
    stage: containerize
    image: docker:25.0.4

    services:
      - docker:dind

    script:
        - docker build -t $CI_REGISTRY_IMAGE:latest .
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker push $CI_REGISTRY_IMAGE:latest
    needs:
        - "build-job"
    only:
        - main

release-job:
    stage: release
    image: docker:25.0.4

    services:
      - docker:dind

    script:
        - docker pull $CI_REGISTRY_IMAGE:latest
        - docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
        - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    
    release:
      tag_name: $CI_COMMIT_TAG
      description: $CI_COMMIT_TAG
      ref: $CI_COMMIT_REF_NAME
  
    only:
        - tags
   