stages:          # List of stages for jobs, and their order of execution
  - build
  - visualize
  - containerize

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: maven:3.9.0-eclipse-temurin-19

  variables:
    MAVEN_CLI_OPTS: "-Dmaven.repo.local=.m2/repository"

  cache:
    paths:
      - .m2/repository

  script:
    - mvn $MAVEN_CLI_OPTS install test package
  artifacts:
    when: always
    reports:
        junit: target/surefire-reports/TEST-*.xml
    paths:
      - target/*.jar


containerize-job:
    stage: containerize
    image: docker:25.0.4

    services:
      - docker:dind

    script:
        - docker build -t $CI_REGISTRY_IMAGE:latest .
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker push $CI_REGISTRY_IMAGE:latest
    needs:
        - "build-job"
    only:
        - main
