version: "3.8"

services:
  frontend:
    image: ghcr.io/shake-the-lake/adminfrontend:main
    ports:
      - 80:80
    depends_on:
      - backend
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SERVER_PATH=/api
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shakethelake
      - SPRING_DATASOURCE_USERNAME=shakethelake
      - SPRING_DATASOURCE_PASSWORD=shakethelake
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_APPLICATION_JSON={"springdoc":{"swagger-ui":{"default-models-expand-depth":-1}}}
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_GENERATE_DDL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_APPLICATION_SHAKETHELAKE_FIREBASE_PRIVATE_KEY=ew0KICAgICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsDQogICAgInByb2plY3RfaWQiOiAic2hha2V0aGVsYWtlIiwNCiAgICAicHJpdmF0ZV9rZXlfaWQiOiAiNDk3YWMxZWQyZjM0ZmZlMDBhNzQyN2JhOWQ4ZWZmMmMxYWIzMDZlNiIsDQogICAgInByaXZhdGVfa2V5IjogIi0tLS0tQkVHSU4gUFJJVkFURSBLRVktLS0tLVxuTUlJRXZRSUJBREFOQmdrcWhraUc5dzBCQVFFRkFBU0NCS2N3Z2dTakFnRUFBb0lCQVFDTnZkTk9jQWo5VFB3T1xuZmhVL3RhM3JsN250K3VBMEkzWUtBRmlGS0o0dlk4cnZsbkoyM3M5cWNNZmlGcVZkQWhRM0NLUGhJTUM5eEsxWFxuclF2bi9PM0pLOVhsRzBIY2JBbnFtdG1Ia3Mwd2lzMDI1NU43dW5ocE5RRisxRzM4VFprUmZRK1BxU2ovaTQ4Z1xueGhNRFovVHBvUXlKYmZjMnYzU0xTMnlsckh2WStaTUJCL3FPeWZoS1ROOURCVlN6V3dqcFJPVUZOUkY2L0FnNlxuUVV5NmlMQUIrT3luODJNdE5pWVpSSUhiekU0Y2gycjlPanRXSjlLeUEzWmZlV0UwUWhQVFltM1lHNFlnUFZ4WVxuQzYzdlFhdkxPYmJqRmNkZlRoWFZVLzh0eWFvVUZFdXU4Rm0zb1QyYUpFaGg4d2M3L21UQi9MR3BsMWcrSGh2U1xucjJucUJEb3hBZ01CQUFFQ2dnRUFDNlJtNGM5ei9aSkFOZFNIWEVkSTlNdnVtcXg3ayt6QnVrcVMrc1QrVVRncVxuS0FtOGR5VVA5bGN6STgvbVgwQlhkcm0vOURMamdmTFFwaDN4bDJtQUFvRVdQWTVDbDU5TUpUZjQzQmpqdjdQMlxuN1NhU1I1eG1YWVhjREpYWVB0d0UwWm5yR0VxMXNsKzlMdHoySE5hQ0dGcUJGQnl6TEkwSFBwWEFZODlLRU9VM1xuck5XT2lqVTM5MndiZTFnYzQ1RlJSMEZ1cVRSS2YxZ3dJa3RPczhNcWxlMm9tdTlCNXNSa2NVbCtESFJzeXVJT1xuOE0wTzlUbHR0NUNtcDhvWXFXYmtOVlZleU15dFBUaFVmYUNIaWpYMG5mMHVpZzkwV0ZERCtxbHh3M2MwK0l1Y1xuWFlXeExJODFvYXhUc3Y0Sk1Semk5MXZId3h6b2lqazRqL0FsK2FzTUVRS0JnUURGYkhvZnZGUUNDRExBWjBwZVxuUUJ6MGo1bFp0a3VkTmdlN3B4ZnpHc0J2WlJ5Uy8yVTdkdi85NExCNml3Mkwra0ZVeWhySHZUTFZMNU5qbnJ5R1xuZE85OHdtN2hNK1JEcXVDNUtMRm1jOGVwczh0WjRacDMvUFlvaVl1ejVHNGU2NThRSVhwK05wT3NjUVFkWExaM1xuQVNKakVQOHlZUDRrV3B0aXk5d0tXamRuMVFLQmdRQzN5L0ozeFpXVVFwTDN2ckV6MEdXbmd5ZFczcm9aK2NnTVxuV1l5QndsQ2hNbDVrd2pIekhNYytjZ2ZFUXlzNWNLZXVySzNOTG9GNkQ5cnNjczJyRWtpUzl6SUlxWkZnNW1ESlxuNWdURGVlSTJ5WmJ6cytxVEVhSStwVndoQXpaVlNhQUp6UzhuaVRidXdqYkptN2hNVzl3OW1nZzlSNFV5bVRDeVxuYUozc1Z1dXk3UUtCZ0FVNGNoNUd0NTM2STRWczljMTZPb25KQmxBVi92ZmdSdUlTY0JLd29XZ1FyMm0vc1NpYVxuWS9pTnFYMEVFazZpUm5uOGdpckgrUUVrS2V5WGRQckZPdFA4dkR2ZVNHbjFxYzJib3QxSHNIN3ZUekJJUS9KcVxuVVFRUFp3OVJ1Z3U5UlU2QzVCOVVTQ0ZtTjZxakdmd1pucFFxRGVXQ0pSWkhBeGJndHlmYTdONGxBb0dCQUlIT1xuRXY5TjF4Y3ZjWFp4QWR0VEtnZ0ZVNnBCZ1BQSmVlUm05aG5LYjRGNC9qdHcveS93dWpLNi9BczdXUEtuUW5YVlxuMUtXZFc2b21PbnBWbGpWa28wYlFPRkR2MlJHemd0WDBrcGF2cFBrR3BJcVhIV3Npd0JBNFh2bWR1Q2pCNTdva1xuWkZJcTBWWU1hZjgyOEJGVnF4VUNqU0VpT3NzQ2IrY0FoZEFkanpiOUFvR0FLbk4vN0pFSXlNSXF1Zno3bk53aVxubUpVM1FFQmVjTzk5OEpMQkpwaGhxR3dOS2h1b1VKck4xY3BSWkErUHNJRE9LRXo1SnhUc3l3Vzh6ZkNJN3VpQ1xuclF1YlhLZWVCWFNNQ2Y3YVBoQ09KR3VtNkVXT0Mybkl1RWlidFRnNFl0SENvakYvZFBqMFVHeWdvVTkxYXJpV1xuRUIvV1dxaFRld2FEZ1VsM3ZoSHNLbzQ9XG4tLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tXG4iLA0KICAgICJjbGllbnRfZW1haWwiOiAiZmlyZWJhc2UtYWRtaW5zZGstMjFuM3lAc2hha2V0aGVsYWtlLmlhbS5nc2VydmljZWFjY291bnQuY29tIiwNCiAgICAiY2xpZW50X2lkIjogIjEwMDA0NjcxNDQ2ODc3MjAxNDIyNCIsDQogICAgImF1dGhfdXJpIjogImh0dHBzOi8vYWNjb3VudHMuZ29vZ2xlLmNvbS9vL29hdXRoMi9hdXRoIiwNCiAgICAidG9rZW5fdXJpIjogImh0dHBzOi8vb2F1dGgyLmdvb2dsZWFwaXMuY29tL3Rva2VuIiwNCiAgICAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsDQogICAgImNsaWVudF94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL3JvYm90L3YxL21ldGFkYXRhL3g1MDkvZmlyZWJhc2UtYWRtaW5zZGstMjFuM3klNDBzaGFrZXRoZWxha2UuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLA0KICAgICJ1bml2ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iDQp9
      - TZ=Europe/Berlin
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_DB=shakethelake
      - POSTGRES_USER=shakethelake
      - POSTGRES_PASSWORD=shakethelake
    ports:
      - "5432:5432"
