version: "3.8"

services:
  frontend:
    image: ghcr.io/shake-the-lake/adminfrontend:main
    ports:
      - 3000:80
#    depends_on:
#      - backend
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SERVER_PATH=/api
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shakethelake
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_APPLICATION_JSON={"springdoc":{"swagger-ui":{"default-models-expand-depth":-1}}}
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_GENERATE_DDL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - TZ=Europe/Berlin
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_DB=shakethelake
      - POSTGRES_USER=shakethelake
      - POSTGRES_PASSWORD=shakethelake
    ports:
      - "5432:5432"
