version: "3.8"

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shakethelake
      - SPRING_DATASOURCE_USERNAME=shakethelake
      - SPRING_DATASOURCE_PASSWORD=shakethelake
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_GENERATE_DDL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=shakethelake
      - POSTGRES_USER=shakethelake
      - POSTGRES_PASSWORD=shakethelake
    ports:
      - "5432:5432"
