version: "3"

services:
  backend:
    image: cr.gitlab.fhnw.ch/ip34-24bb/ip34-24bb_shakethelake/shakethelakebackend:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shakethelake
      - SPRING_DATASOURCE_USERNAME=shakethelake
      - SPRING_DATASOURCE_PASSWORD=shakethelake

  postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_DB=shakethelake
      - POSTGRES_USER=shakethelake
      - POSTGRES_PASSWORD=shakethelake
    ports:
      - "5432:5432"
