version: "3"

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shakethelake
      - SPRING_DATASOURCE_USERNAME=shakethelake
      - SPRING_DATASOURCE_PASSWORD=shakethelake
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=shakethelake
      - POSTGRES_USER=shakethelake
      - POSTGRES_PASSWORD=shakethelake
    ports:
      - "5432:5432"
