version: "3.8"

# Due to limitation in azure app service of only having one port exposed
# this setup tries to use a reverse proxy to expose the frontend and backend
# on the same port but different paths

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.4
    # Enables the web UI and tells Traefik to listen to docker
    command:
     # Enabling docker provider
      - '--providers.docker'
      # Do not expose containers unless explicitly told so
      - '--providers.docker.exposedbydefault=false'
      - '--entryPoints.80-web.address=:80'
      - '--providers.docker.constraints=Label(`custom.label`,`shakethe`)'
    ports:
      # The HTTP port
      - 80:80
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  frontend:
    image: ghcr.io/shake-the-lake/adminfrontend:main
    depends_on:
      - backend
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.frontend.rule=PathPrefix(`/`)'
      - 'custom.label=shakethe'
  backend:
    image: ghcr.io/shake-the-lake/adminbackend:sha-8274e57
    environment:
      - SERVER_PORT=8080
      - SERVER_PATH=/api
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shakethelake
      - SPRING_DATASOURCE_USERNAME=shakethelake
      - SPRING_DATASOURCE_PASSWORD=shakethelake
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_APPLICATION_JSON={"springdoc":{"swagger-ui":{"default-models-expand-depth":-1}}}
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_GENERATE_DDL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - TZ=Europe/Berlin
    depends_on:
      - db
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.backend.rule=PathPrefix(`/api`)'
      - 'traefik.http.services.backend.loadbalancer.server.port=8080'
      - 'custom.label=shakethe'
  db:
    image: postgres:latest
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_DB=shakethelake
      - POSTGRES_USER=shakethelake
      - POSTGRES_PASSWORD=shakethelake
    labels:
      - 'custom.label=shakethe'
